project:
  type: website

website:
  title: "Phuong Luong"
  navbar:
    background: "#102f2a"
    foreground: "#ffffff"
    left:
      - text: About
        href: about.qmd
      - text: Personal Work
        href: projects.qmd
      - text: Skills
        href: skills.qmd
      - text: Experience
        href: experience.qmd
      - text: Contact
        href: contact.qmd

format:
  html:
    theme: none
    css: styles.css
    toc: false
    page-layout: full
    title-block-banner: false
